In [28]:
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import os, sys
import multiprocessing
%matplotlib inline

In [30]:
multiprocessing.cpu_count()

16

In [2]:
os.getcwd()
os.chdir('C:\\Users\\Ben\\Documents\\682_project')

In [19]:
with open('data/self_play/captains_mode_vs_random_memory.pickle', 'rb') as f:
    mem = pickle.load(f)
w

In [20]:
mem[0].keys()

dict_keys(['all_actions', 'all_states', 'all_values', 'all_agent_pick_first'])

In [21]:
all_outcomes = []
all_agent_pick_first = []
for m in mem:
    all_outcomes.extend(m['all_values'])
    all_agent_pick_first.extend(m['all_agent_pick_first'])

In [22]:
all_outcomes = np.array(all_outcomes)
missing = all_outcomes != None
all_outcomes = all_outcomes[missing]
all_agent_pick_first = np.array(all_agent_pick_first)
all_agent_pick_first = all_agent_pick_first[missing]

In [23]:
np.mean(all_outcomes[all_outcomes is not None])

0.5747126436781609

In [24]:
all_outcomes[:5]

array([1, 1, 1, 1, 1], dtype=object)

In [25]:
(all_outcomes == all_agent_pick_first).mean()

0.39080459770114945

In [27]:
mem[0]['all_states'][-1]

array([  2.,  56.,  91.,  97., 115., 102.,  25.,  59.,  63.,   4.,  27.,
        49.,   2.,  65.,  24.,  83.,  93., 103., 112.,  85., 107.,  78.,
        39., 100.,   2.])

In [12]:
states[-1].radiant

array([86.,  3., 35., 55., 85.])

In [13]:
states[-1].dire

array([33., 19., 16., 66.,  2.])

In [14]:
actions

[6,
 14,
 72,
 48,
 10,
 41,
 86,
 33,
 3,
 19,
 82,
 95,
 97,
 92,
 35,
 16,
 55,
 66,
 84,
 7,
 85,
 69]